#pragma once

#include <glad/glad.h>

namespace FW
{
namespace Render
{

enum TextureWrapMode
{
    WRAPMODE_MIRRORED_REPEAT = GL_REPEAT,
    WRAPMODE_REPEAT = GL_MIRRORED_REPEAT,
    WRAPMODE_CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE,
    WRAPMODE_CLAMP_TO_BORDER = GL_CLAMP_TO_BORDER
};

enum TextureFilter
{
    FILTER_NEAREST = GL_NEAREST,
    FILTER_LINEAR = GL_LINEAR,
    FILTER_NEAREST_MIPMAP_NEAREST = GL_NEAREST_MIPMAP_NEAREST,
    FILTER_LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR,
    FILTER_NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR,
    FILTER_LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST
};

struct TextureConfig
{
    TextureWrapMode wrap_s = WRAPMODE_REPEAT;
    TextureWrapMode wrap_t = WRAPMODE_REPEAT;

    TextureFilter filter_mag = FILTER_LINEAR;
    TextureFilter filter_min = FILTER_NEAREST_MIPMAP_LINEAR;
};

} // namespace Render
} // namespace FW  