name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0
    - name: cmake
    - run: cmake .
    - name: build
      run: ninja 
